FROM node:20-alpine

WORKDIR /app

# Install netcat for health check
RUN apk add --no-cache netcat-openbsd

# Copy workspace files
COPY package.json ./
COPY apps ./apps
COPY libs ./libs

ENV NODE_ENV=development
RUN npm install

WORKDIR /app/apps/user-service

# Copy wait script
COPY apps/user-service/wait-for-mysql.sh /wait-for-mysql.sh

EXPOSE 3000

CMD ["/wait-for-mysql.sh", "npm", "run", "dev"]
