FROM node:20-alpine
WORKDIR /app

# Copy root and service package.json files
COPY package.json package-lock.json ./
COPY apps ./apps
COPY libs ./libs
# Copy libraries
ENV NODE_ENV=development
RUN npm install
WORKDIR /app/apps/storage-service
EXPOSE 50051
CMD ["npm", "run", "dev"]
